apiVersion: v1
kind: Secret

metadata:
  name: mysql-secret
  namespace: expense-dev

type: Opaque

data:
   MYSQL_ROOT_PASSWORD: RXhwZW5zZUAxMjM=   #Expense@123
   MYSQL_DATABASE: ZXhwZW5zZV9kYg==       #expense_db
   MYSQL_USER: ZXhwZW5zZV9hcHA=        #expense_app
   MYSQL_PASSWORD: RXhwZW5zZUAxMjM=       #Expense@123


   #[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("Expense@123"))