apiVersion: v1
kind: ConfigMap

metadata:
   name: expense-config
   namespace: expense-dev
data:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-service:3306/expense_db
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
  SPRING_JPA_HIBERNATE_DDL_AUTO: update
  SPRING_JPA_SHOW_SQL: "true"