apiVersion: v1
kind: Secret

metadata:
  name: expense-secret
  namespace: expense-dev

type: Opaque

data:
  SPRING_DATASOURCE_USERNAME: ZXhwZW5zZV9hcHA=
  SPRING_DATASOURCE_PASSWORD: RXhwZW5zZUAxMjM=

  #[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes("Expense@123"))